### ISSUE TITLE
W3 - Commenting system

### ISSUE THREAD

**Issue by iskapoor** [iskapoor/group-l#41]
Create a commenting feature for blogs to allow users to talk about the blog to the blog writer or other readers.

**Comment by algolg** [comment]
Commit: https://github.com/iskapoor/group-l/commit/f17a078a90000b10c63f18c1bcbaa8dde38fad3f
As seen on the blog template page (/temp). A comment section like this one will be found on all blog pages.
The goal is to get rid of the username input field once we implement a user database (at which point it would use a user's actual username rather than prompt users for their names).
![image](https://user-images.githubusercontent.com/55261146/146315394-8994cee3-86f0-4fbd-947a-4a2b8041df7b.png)
